#
# Build stage
#
FROM maven:ibmjava-alpine AS build_java
WORKDIR /build

COPY . .

RUN mvn package -Dmaven.test.skip

#
# Package stage
#
FROM openjdk:8-alpine
WORKDIR /app

COPY --from=build_java /build/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]